name: Creative workflows1

on:
   pull_request:
     branches:
          -master
workflow_dispatch
jobs:
    perform-action:
          runs-on: ubuntu-latest
          steps:
          - name: First interaction
            uses: actions/first-interaction@v1.1.1
            with :
            pr-message: 'Thanks for your contribution.

            Remember-The measure of intelligence is the ability to change'
